name: tontine_calendar_example
description: Example app for the TontineCalendar package
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tontine_calendar:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
